### ISSUE TITLE
Group Selection

### ISSUE THREAD

**Issue by WinDroidGuy** [mitchmcdee/LifxController#11]
If there's a group, can the "individual" lights not show up or have an option to disable them? This would cause less clutter. The new group options also made my 4th light not show up, while I still see it in the app & within another app I use.

http://imgur.com/a/cujen

**Comment by mitchmcdee** [comment]
Will open a new issue for a 'Settings' feature request. 

Could you provide some more details on the second issue? Was the light appearing before and now it's not? Does restarting the app or turning the light on and off fix anything?

**Comment by WinDroidGuy** [comment]
Yes, the light was there prior to updating. I can toggle on/off from my phone or Lighting app; but still doesn't show up in the status bar.

**Comment by mitchmcdee** [comment]
Cool :) Will close this issue for mean time, let me know if there are any more issues!
