### ISSUE TITLE
Discovery 

### ISSUE THREAD

**Issue by Papeeps** [mitchmcdee/LifxController#16]
After running the program, it is only finding one of twelve lights.

**Comment by mitchmcdee** [comment]
Am about to launch a new verison, curious to see if this helps you :)

**Comment by Papeeps** [comment]
The new version found all lights.  Thank you.  Discovery was a little slow each time I clicked on the controller icon.  The pinwheel would spin for 30 seconds or so.  Thank you!

**Comment by mitchmcdee** [comment]
Fantastic that's great to hear :)

Yeah unfortunately discovery is just a pain in the butt with the library i'm using bahahaha, so improvements there are limited. I have added #18 as a potential route for alleviation :)
