### ISSUE TITLE
Add support for groups

### ISSUE THREAD

**Issue by mitchmcdee** [mitchmcdee/LifxController#3]
As per title

**Comment by mitchmcdee** [comment]
Optionally (or additionally), support groups?

**Comment by WinDroidGuy** [comment]
I'd prefer groups; I've got a group & would rather have that individual lights showing up.

**Comment by mitchmcdee** [comment]
I think that's the best option too :)

**Comment by mitchmcdee** [comment]
Added in d990ef5a736a126b055555a92434fce17fd41287 :)
