### ISSUE TITLE
No Menu Options except Quit

### ISSUE THREAD

**Issue by Papeeps** [mitchmcdee/LifxController#5]
After install, my only menu option is to "Quit"

**Comment by mitchmcdee** [comment]
Seems its not discovering your bulbs for whatever reason :\

I'm releasing a new version in about a day, if the issue still persists after then (and your bulbs are definitely on!) we can investigate some debugging options

**Comment by mitchmcdee** [comment]
Okay new update released! Let me know if that fixes anything for you :)

**Comment by Papeeps** [comment]
I am now able to discover the lights and groups.  Very nice.  Than you.  When I turn off a group, the individual light still shows as "On" even though it is actually off.

**Comment by mitchmcdee** [comment]
Light states should update every 2 seconds, does is persistently say that's on when it should be off?

**Comment by Papeeps** [comment]
It is persistently off.

**Comment by mitchmcdee** [comment]
I'll make a new issue for it as I've noticed it sometimes too-- will close this one :)
