### ISSUE TITLE
LifxController fails to start

### ISSUE THREAD

**Issue by cwhowell** [mitchmcdee/LifxController#9]
LifxController does not start on Mac OS X El Capitan, version 10.11.6. Crash log from Console is attached. It mentions the following error text:

> Dyld Error Message:
>   Symbol not found: _getentropy
>   Referenced from: /Applications/LifxController.app/Contents/Frameworks/Python.framework/Versions/2.7/Python (which was built for Mac OS X 10.12)
>   Expected in: /usr/lib/libSystem.B.dylib

I'm not particularly familiar with Py2App, could this be because I'm not running Sierra? I plan to upgrade soon so can test if that fixes the issue. I have updated OS X's built in Python, so I guess that could be related, but it looks like you're packaging your own version in the app.

[LifxController_2017-03-25.txt](https://github.com/mitchmcdee/LifxController/files/869738/LifxController_2017-03-25.txt)

**Comment by mitchmcdee** [comment]
Interesting. I'm new to py2app so it's possible its being tailor built to Sierra. I also had to have a custom library-- which could also be tailored to Sierra.

I'll investigate this issue more, in the mean time it'd be great if you could get back to me on whether upgrading fixes it :)

**Comment by cwhowell** [comment]
Finally got around to upgrading to Sierra and the issue no longer occurs - LifxController starts up and works as intended.

**Comment by mitchmcdee** [comment]
Closing for now but will re-open if this needs further investigation
